name: Bug report
description: Сообщить об ошибке
title: "[bug] "
labels: ["bug"]
body:
  - type: textarea
    attributes:
      label: Описание
      placeholder: Что происходит не так?
  - type: textarea
    attributes:
      label: Шаги воспроизведения
  - type: textarea
    attributes:
      label: Ожидаемое поведение
  - type: textarea
    attributes:
      label: Скриншоты/логи
